apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app.kubernetes.io/name: backend
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.Version }}
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: momo-store
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    env: {{ .Values.environment }}
    app: backend
spec:
  replicas: {{ .Values.replicaCount }}
  # Стратегия развёртывания. Recreate — удалит сначала все старые Pod'ы 
  # Есть и более гибкая стратегии, например, RollingUpdate, которая будет обновлять Pod'ы порциями  
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 20% 
  selector:
    matchLabels:
      app: backend
  revisionHistoryLimit: 15
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: backend
              containerPort: 8081
          resources: 
{{ toYaml .Values.resources | indent 12 }}
      imagePullSecrets:
        - name: docker-config-secret
