# Секрет, необходимый, чтобы взаимодействовать с Docker Registry в GitLab:
---
kind: Secret
apiVersion: v1
metadata:
  name: docker-config-secret
data:
  .dockerconfigjson: eyJhdXRocyI6eyJhcnRlbW1paGF5bG92LmdpdGxhYi55YW5kZXhjbG91ZC5uZXQ6NTA1MCI6eyJhdXRoIjoiWVhKMFpXMXRhV2hoZVd4dmRqQXdPbTF2Ylc4dGMzUnZjbVV0WVhKMFpXMXBhMmhoZVd4dmRnPT0ifX19
type: kubernetes.io/dockerconfigjson